.catalog:
  name: "3-tier-web-glb"
  version: "v1.0"
  questions:
    - variable: "DB_HOST"
      label: "DB Host"
      description: DB Host for app"
      type: "string"
      default: "172.31.15.213"
      required: true

qly:
  scale: 1
  start_on_create: true
